### ISSUE TITLE
Wrong type hint for "pool_or_conn" parameter

### ISSUE THREAD

**Issue by Ronserruya** [mrasband/aioredis-lock#1]
https://github.com/mrasband/aioredis-lock/blob/master/aioredis_lock/locks.py#L28

```python
pool_or_conn: ConnectionsPool
```
Should be 
```python
pool_or_conn: Union[ConnectionsPool, Redis, RedisConnection]
```

Also, the Readme should say that the "Redis" type is also accepted unless I miss something, it works for me

Obviously doesn't affect functionality, but it's nice to be more precise :)

Ps. This lib works great, thx for the work you put into it :+1:

**Comment by mattrasband** [comment]
Thanks for that, I will get this updated!

**Comment by mattrasband** [comment]
I made this just the `aioredis.commands.Redis` interface since we depend on it being a redis connection with the commands mixins applied. Thanks for the head's up!
